# Generated by Django 4.1.4 on 2023-02-08 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The Contributor's first name", max_length=50)),
                ('last_name', models.CharField(help_text="The contributor's last name or name", max_length=50)),
                ('email', models.EmailField(help_text='The contact email for the contributor.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MovieContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], max_length=20, verbose_name='The role this contributor had in the movie.')),
                ('Contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Movie.', max_length=100)),
                ('data', models.DateField(verbose_name='Data the movie was released')),
                ('contributor', models.ManyToManyField(through='MoviesListApp.MovieContributor', to='MoviesListApp.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Publisher.', max_length=50)),
                ('website', models.URLField(help_text="The Publisher's website.")),
                ('email', models.EmailField(help_text="The Publisher's email address.", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, help_text='The date and time the review was created.')),
                ('contact', models.TextField(help_text='The Review text.')),
                ('rating', models.IntegerField(help_text='The rating the reviewer has given')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(help_text='The Movie that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.movies_info')),
            ],
        ),
        migrations.AddField(
            model_name='movies_info',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.publisher'),
        ),
        migrations.AddField(
            model_name='moviecontributor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.movies_info'),
        ),
    ]
